name: Build, test and publish
on:
  push:
    branches:
      - master

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-2022
      use-msbuild: true
      workloads: maui
      project-path: 
        # This is required for correct publishing to NuGet
        /target:libs\H_GeneratedIcons_SkiaSharp
        /target:libs\H_GeneratedIcons_System_Drawing
        /target:libs\H_NotifyIcon
        /target:libs\H_NotifyIcon_Uno
        /target:libs\H_NotifyIcon_Uno_WinUI
        /target:libs\H_NotifyIcon_WinUI
        /target:libs\H_NotifyIcon_Wpf
        /target:libs\H_NotifyIcon_Maui
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
